apiVersion: apps/v1
kind: Deployment
metadata:
  name: lrfedeployment
  namespace: frontendlr
spec:
  selector:
    matchLabels:
      app: learnerreport
  template:
    metadata:
      labels:
        app: learnerreport
    spec:
      containers:
      - name: lrfedeployment
        image: ravikishans/learnerreport:frontend
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: lr-config
              key: REACT_APP_BACKEND_URL
        ports:
        - containerPort: 3000
