apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.backend.namespace }}
data:
  MONGO_URI: {{ .Values.backend.env.MONGO_URL | b64enc }}
  # mongodb://mongodb-service.databaselr.svc.cluster.local:27017/learnerreport
type: Opaque
