apiVersion: v1
kind: ConfigMap
metadata:
  name: lr-config
  namespace: {{ .Values.frontend.namespace }}
  labels:
    app: learnerreport
data:
  REACT_APP_BACKEND_URL: {{ .Values.frontend.data.REACT_APP_BACKEND_URL }}