apiVersion: apps/v1
kind: Deployment
metadata:
  name: lrfedeployment
  namespace: {{ .Values.frontend.namespace }}
spec:
  selector:
    matchLabels:
      app: learnerreport
  template:
    metadata:
      labels:
        app: learnerreport
    spec:
      containers:
      - name: lrfedeployment
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: lr-config
              key: REACT_APP_BACKEND_URL
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
