apiVersion: v1
kind: Service
metadata:
  name: lrfeservice
  namespace: {{ .Values.frontend.namespace }}
spec:
  selector:
    app: learnerreport
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
